bootstrap.servers=pkc-43n10.us-central1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="RG7FLNWQDX5P3I7P" password="OdfZYkecbHA9uXICfXUN/S8nGQFGxNg2ODedbLkYxtFMZ9dkeX6kJ4ojW1hnsQXs";
sasl.mechanism=PLAIN
acks=all
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=starter-consumer-2
enable.auto.commit=false